"""add recharge table

Revision ID: 015025f75db6
Revises: 7f836abf00ae
Create Date: 2020-12-28 22:16:16.290070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015025f75db6'
down_revision = '7f836abf00ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mf_user_recharge',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称/标题'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('orders', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态(是否支付)'),
    sa.Column('out_trade_number', sa.String(length=64), nullable=True, comment='订单号'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
    sa.Column('money', sa.Numeric(precision=7, scale=2), nullable=True, comment='账户余额'),
    sa.Column('trade_number', sa.String(length=64), nullable=True, comment='流水号'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('out_trade_number'),
    sa.UniqueConstraint('trade_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mf_user_recharge')
    # ### end Alembic commands ###
