"""update user data

Revision ID: 68ec7de2ee09
Revises: 792f001acd9e
Create Date: 2020-12-15 19:17:14.749263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68ec7de2ee09'
down_revision = '792f001acd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mf_user_relation', sa.Column('relation_status', sa.Integer(), nullable=True, comment='关系状态'))
    op.alter_column('mf_user_relation', 'receive_user',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户2',
               existing_comment='用户ID2',
               existing_nullable=True)
    op.alter_column('mf_user_relation', 'send_user',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户1',
               existing_comment='用户ID1',
               existing_nullable=True)
    op.alter_column('mf_user_relation', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='状态(是否显示,是否激活)',
               existing_comment='关系状态',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mf_user_relation', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='关系状态',
               existing_comment='状态(是否显示,是否激活)',
               existing_nullable=True)
    op.alter_column('mf_user_relation', 'send_user',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID1',
               existing_comment='用户1',
               existing_nullable=True)
    op.alter_column('mf_user_relation', 'receive_user',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID2',
               existing_comment='用户2',
               existing_nullable=True)
    op.drop_column('mf_user_relation', 'relation_status')
    # ### end Alembic commands ###
