"""add goods column

Revision ID: 6d36f153a1f4
Revises: 015025f75db6
Create Date: 2020-12-30 19:23:31.650725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d36f153a1f4'
down_revision = '015025f75db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mf_goods', sa.Column('credit', sa.Integer(), nullable=True, comment='商品价格[果子]'))
    op.alter_column('mf_goods', 'price',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               comment='商品价格[余额]',
               existing_comment='商品价格',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mf_goods', 'price',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               comment='商品价格',
               existing_comment='商品价格[余额]',
               existing_nullable=True)
    op.drop_column('mf_goods', 'credit')
    # ### end Alembic commands ###
