"""add user guanxi

Revision ID: 792f001acd9e
Revises: 8b2c6d6ba374
Create Date: 2020-12-14 21:43:32.237046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792f001acd9e'
down_revision = '8b2c6d6ba374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mf_user_relation',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称/标题'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('orders', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('send_user', sa.Integer(), nullable=True, comment='用户ID1'),
    sa.Column('receive_user', sa.Integer(), nullable=True, comment='用户ID2'),
    sa.Column('relation_type', sa.Integer(), nullable=True, comment='构建关系类型'),
    sa.Column('status', sa.Integer(), nullable=True, comment='关系状态'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mf_user_relation')
    # ### end Alembic commands ###
