"""add goods table

Revision ID: 7f836abf00ae
Revises: 68ec7de2ee09
Create Date: 2020-12-28 19:27:39.074850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f836abf00ae'
down_revision = '68ec7de2ee09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mf_goods',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称/标题'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('orders', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态(是否显示,是否激活)'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='商品描述'),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=True, comment='商品价格'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='商品图片'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mf_user', sa.Column('credit', sa.Numeric(precision=7, scale=2), nullable=True, comment='果子积分'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mf_user', 'credit')
    op.drop_table('mf_goods')
    # ### end Alembic commands ###
