"""add live table

Revision ID: f185fdc5fc16
Revises: ab9be91f5607
Create Date: 2021-01-11 21:13:35.246267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f185fdc5fc16'
down_revision = 'ab9be91f5607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mf_live_room',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称/标题'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('orders', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态(是否显示,是否激活)'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('stream_id', sa.Integer(), nullable=True, comment='直播流ID'),
    sa.Column('user', sa.Integer(), nullable=True, comment='用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mf_live_stream',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除'),
    sa.Column('orders', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态(是否显示,是否激活)'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='流名称'),
    sa.Column('room_name', sa.String(length=255), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True, comment='房主'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mf_live_stream')
    op.drop_table('mf_live_room')
    # ### end Alembic commands ###
